### ISSUE TITLE
fix: optional parameters default to *, which raises Exceptions

### ISSUE THREAD

**Issue by bademaister** [ieeh-tu-dresden/powerfactory-utils#36]
I recently discovered the project and find it very interesting, so I tested it and would like to help you with a bug report.

The PowerfactoryExporter as well as the export_powerfactory_data have the optional parameters _grid_name_ and _powerfactory_user_profile_ which defaults are _*_.

A call with an empty _powerfactory_user_profile_ will fail as in the further process you call pf.GetApplicationExt with the default value of *, which will raise a powerfactory.ExitError with error code 5000.

Similiar issue with an empty _grid_name_ parameter.
export method of the PowerFactoryExporter instance has optional parameters _topology_name_, _topology_case_name_, _steadystate_case_name_.
With no _topology_name_ supplied, export_topology tries to create a json file with _grid_name_. Which, if empty, defaults to *, which
is not a valid character for a file under windows.

cheers

Paul

**Comment by sasanjac** [comment]
Hi Paul, thanks a lot for your bug report.

I've made `grid_name` required now, since to my understanding there is no point in leaving that empty. `user_name` now defaults to `""` which is fine, if only one user is using the database.

And finally, the export paths are checked if valid and an error is logged if not.

**Comment by sasanjac** [comment]
Oh thank you. I'll reopen.
